<%@ Page Title="Galeria de Imagenes" Language="C#" MasterPageFile="~/Principal.Master" AutoEventWireup="true" CodeBehind="Galeria.aspx.cs" Inherits="MusebeWEBFinal.Galeria" %>
<%@ Register assembly="DevExpress.Web.v14.2, Version=14.2.15.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" namespace="DevExpress.Web" tagprefix="dx" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <dx:ASPxFileManager ID="uplGaleriaFotos" runat="server" EnableCallbackAnimation="True" EnableTheming="True" Theme="Metropolis" Width="100%">
        <ClientSideEvents CustomCommand="function(s, e) {
 switch(e.commandName) {
          case &quot;VistaPrevia&quot;:
                cbp.PerformCallback();
              	popupVistaPrevia.Show();
               break;
          case &quot;ChangeView-Details&quot;:
               FileManager.PerformCallback(&quot;Details&quot;);
               break;
     }	
}" />
        <Settings RootFolder="~\msbear\images\galeriaimagenes\" ThumbnailFolder="~\Thumb\" />
        <SettingsEditing AllowDelete="True" AllowDownload="True" />
        <SettingsToolbar>
            <Items>
                <dx:FileManagerToolbarCustomButton CommandName="VistaPrevia" Text="Vista Previa">
                </dx:FileManagerToolbarCustomButton>
            </Items>
        </SettingsToolbar>
        <SettingsUpload>
            <AdvancedModeSettings EnableMultiSelect="True">
            </AdvancedModeSettings>
        </SettingsUpload>
    </dx:ASPxFileManager>
    <dx:ASPxPopupControl ID="popupVistaPrevia" runat="server" AllowDragging="True" AllowResize="True" AutoUpdatePosition="True" ClientInstanceName="popupVistaPrevia" EnableCallbackAnimation="True" HeaderText="Vista Previa" Maximized="True" Modal="True" PopupHorizontalAlign="WindowCenter" PopupVerticalAlign="WindowCenter" ShowMaximizeButton="True" ShowPageScrollbarWhenModal="True">
        <ContentCollection>
<dx:PopupControlContentControl runat="server">
    <dx:ASPxCallbackPanel ID="cbp" runat="server" ClientInstanceName="cbp" Height="100%" Width="100%">
        <PanelCollection>
            <dx:PanelContent runat="server">
                <dx:ASPxImageSlider ID="SliderGaleria" runat="server" ClientInstanceName="SliderGaleria" ImageSourceFolder="~/msbear/images/galeriaimagenes/" SeoFriendly="True" Width="100%">
                    <SettingsImageArea EnableLoopNavigation="True" />
                    <SettingsBehavior AllowMouseWheel="True" />
                    <SettingsSlideShow AutoPlay="True" PlayPauseButtonVisibility="Always" />
                    <SettingsAutoGeneratedImages ImageCacheFolder="~\Thumb\" />
                </dx:ASPxImageSlider>
            </dx:PanelContent>
        </PanelCollection>
    </dx:ASPxCallbackPanel>
    <br />
            </dx:PopupControlContentControl>
</ContentCollection>
    </dx:ASPxPopupControl>
    <br />
</asp:Content>
